version: '1.0.{build}'
image:
- Visual Studio 2017
- Visual Studio 2019

platform: Any CPU
environment:
  DOTNET_CLI_TELEMETRY_OPTOUT: 1
init:
- cmd: bash -c 'time echo "Hello from BASH $(bash --version)"'
- ps: |
    Set-Service RemoteAccess -StartupType Manual
    Start-Service RemoteAccess
    Set-Service NetTcpPortSharing -StartupType Manual
    Start-Service NetTcpPortSharing
- ps: | 
        netsh advfirewall firewall add rule name="All ICMP V4" protocol=icmpv4:any,any dir=in action=allow
        netsh advfirewall firewall add rule name="Open Port 1433 (SQL Servers)" dir=in action=allow protocol=TCP localport=1433


before_build:
# - appveyor-retry dotnet restore -v Minimal
- ps: |
    $names = @();
    foreach($path in @('HKLM:\SOFTWARE\Microsoft\Microsoft SQL Server', 'HKLM:\SOFTWARE\WOW6432Node\Microsoft\Microsoft SQL Server')) {
        try { $v = (get-itemproperty $path).InstalledInstances; $names += $v } catch {}
    }

    [System.Array]::Sort($names);
    $info=""; foreach($name in $names) { $info += " [$name]"; } Write-Host "Sql Servers: $info";
    foreach($sqlname in $names) {
        if ($sqlname.Length -eq 0) { continue; }
        "Disable MSSQL`$$sqlname"
        Set-Service "MSSQL`$$sqlname" -StartupType Disabled
    }
    get-wmiobject win32_service | where {$_.Name.ToLower().IndexOf("sql") -ge 0 } | sort-object -Property "DisplayName" | ft Name, DisplayName, StartMode, State
    cmd /c dir /b /s

- ps: | 
        pushd SQL-Express; 
        .\SQL-Express-2017-Updated.cmd 
        .\SQL-Express-2014-SP2-x86.cmd
        .\SQL-Express-2012-SP3.cmd
        .\SQL-Express-2008-R2-SP2-x86.cmd
        popd

        get-wmiobject win32_service | where {$_.Name.ToLower().IndexOf("sql") -ge 0 } | sort-object -Property "DisplayName" | ft Name, DisplayName, StartMode, State

build_script:
- ps: .\build-and-test.cmd
# - ps: cd KernelManagementJam.Tests
# - dotnet --info
# - dotnet build -c %CONFIGURATION% 

after_build:
# - echo Im AFTER a BUILD. Nothing todo
test_script:
# none
artifacts:
# - path: artifacts\**\*.*
cache:
# - '%USERPROFILE%\.nuget\packages'
on_finish: # Run the demo to show that it works
# - dotnet artifacts\ConsoleApplication\ConsoleApplication.dll
