version: 2

jobs:
  build:
    machine: true
#    docker:
#      - image: mono:6.4
    steps:
      - checkout
      - run: 'curl -I https://google.com'
      - run: 'apt -q update >/dev/null ; apt install -y -q git sudo jq tar bzip2 gzip curl lsb-release procps'
      - run: git submodule update --init --recursive
      - run: nuget restore
      - run: 'pushd include/Universe.SqlServerJam/src; nuget restore; popd'
      - run: msbuild Universe.SqlTrace.sln
      - run: 'url=https://raw.githubusercontent.com/devizer/glist/master/install-docker-on-debian.sh; (wget -q -nv --no-check-certificate -O - $url 2>/dev/null || curl -sSL $url) | bash'
      - run: 'docker run -t hello-world || true'
      - run: '/usr/bin/dockerd -H unix:///var/run/docker.sock || true'
      # /usr/bin/dockerd -H fd:// --containerd=/run/containerd/containerd.sock
      # 
  test:
    docker:
      - image: mono:6.4
    steps:
      - checkout
      - run: echo Not yet implemented

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test
