version: 2

jobs:
  build:
    machine: true
#    docker:
#      - image: mono:6.4
    steps:
      - checkout
      - run: 'curl -I https://google.com'
      - run: 'sudo apt -q update >/dev/null ; sudo apt install -y -q git sudo jq tar bzip2 gzip curl lsb-release procps'
      - run: git submodule update --init --recursive
      - run: 'lscpu || true'
      - run: 'free -m'
      - run: 'cat /etc/os-release'
      - run: |
            apt-cache policy mono-complete; apt-cache policy nuget; apt-cache policy msbuild;
      - run: |
            echo 'Acquire::Check-Valid-Until "0";' | sudo tee /etc/apt/apt.conf.d/10no--check-valid-until
            echo 'APT::Get::Assume-Yes "true";' | sudo tee /etc/apt/apt.conf.d/11assume-yes
            echo 'APT::Get::AllowUnauthenticated "true";' | sudo tee /etc/apt/apt.conf.d/12allow-unauth

            if [[ "$(command -v mono)" == "" ]]; then 
              # sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys A6A19B38D3D831EF
              # sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 3FA7E0328081BFF6A14DA29AA6A19B38D3D831EF
              source /etc/os-release
              def="deb https://download.mono-project.com/repo/$ID stable-$(lsb_release -s -c) main"
              if [[ "$ID" == "raspbian" ]]; then def="deb https://download.mono-project.com/repo/debian stable-raspbian$(lsb_release -cs) main"; fi
              echo "$def" | sudo tee /etc/apt/sources.list.d/mono-official-stable.list
              ## sudo apt-get --allow-unauthenticated update && time sudo apt-get --allow-unauthenticated install mono-complete nuget msbuild -y -q
              sudo apt-get update; time sudo apt-get install mono-complete nuget msbuild -y -q
            fi
            echo "ok?"
      - run: |
            apt-cache policy mono-complete; apt-cache policy nuget; apt-cache policy msbuild;

      - run: nuget restore
      - run: 'pushd include/Universe.SqlServerJam/src; nuget restore; popd'
      - run: msbuild Universe.SqlTrace.sln
      # - run: 'url=https://raw.githubusercontent.com/devizer/glist/master/install-docker-on-debian.sh; (wget -q -nv --no-check-certificate -O - $url 2>/dev/null || curl -sSL $url) | bash'
      - run: 'sudo docker run -t hello-world || true'
      - run: 'docker run -t hello-world || true'
      - run: 'sudo docker version'
      - run: 'docker version'
      # - run: '/usr/bin/dockerd -H unix:///var/run/docker.sock || true'
      # /usr/bin/dockerd -H fd:// --containerd=/run/containerd/containerd.sock
      # 
  test:
    docker:
      - image: mono:6.4
    steps:
      - checkout
      - run: 'cat /etc/os-release'

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test
